version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Gradle dependencies...
      - gradle build --refresh-dependencies

  build:
    commands:
      - echo Building the project...
      - gradle build

  post_build:
    commands:
      - echo Preparing deployment artifacts...
      # Rename the built JAR to a fixed name (Elastic Beanstalk likes that)
      - mkdir -p output
      - cp build/libs/*.jar output/student-admission-cli.jar
      - cp Procfile output/

artifacts:
  files:
    - output/**/*
