version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Gradle dependencies...
      - gradle build --refresh-dependencies

  build:
    commands:
      - echo Building the project...
      - gradle build

  post_build:
    commands:
      - echo Running tests...
      - gradle test
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/student-admission-cli.jar
  discard-paths: yes
