version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - gradle build --refresh-dependencies
  build:
    commands:
      - echo Running unit tests...
      - gradle test
